### PR TITLE
Move presenter content to site.data

### PR DESCRIPTION
**Pull request by jmhobbs**
This is in reference to #14.

I found that moving the presenter code to a Jekyll plugin wouldn't really change anything, and we would have to port a lot of the existing code from JS to Ruby.

So instead, I broke the data out of the JS templates and injected it into Jekyll through the <tt>site.data</tt>.

This is incomplete right now, there are some edge cases to solve, like dual-presenter avatars.  I'm just opening this PR for discussion.

### CODE REVIEW

**Comment by jmhobbs** [comment]
Fixed the multiple author avatar thing.  This is ready for review and comment :)

There are some other things we _could_ do, like move presenter data to `_config.yml` or something, odds and ends to reduce the amount of JS ran, but I'm okay with it as is.

**Comment by jmhobbs** [comment]
I decided to move the presenters into a single, in-place updated YAML file.  I think it's more readable because it groups the user attributes together in the file.

**Comment by jmhobbs** [comment]
Thoughts @zachleat?

**Comment by zachleat** [comment]
Merged, thanks! Somehow I didn’t see this until you closed it—sorry 😱

**Pull request merged**
